### ISSUE TITLE
autocomplete.js

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/Mario-Market#3]
1) You don't need `__dirname` [here](https://github.com/WebAhead12/Mario-Market/blob/main/handlers/autocomplete.js#L6-L7)
2) use `path` [here](https://github.com/WebAhead12/Mario-Market/blob/main/handlers/autocomplete.js#L6-L7) for consistent execration between operating systems, and generally a better practice to always use path
3) I feel like if [this runs once](https://github.com/WebAhead12/Mario-Market/blob/main/handlers/autocomplete.js#L10-L21) then it would be better if we have it in `server.js` or a file on it's own like `utils`
4) This doesn't matter for now, but next time use `.filter`, you can also connect filters together, https://github.com/WebAhead12/Mario-Market/blob/main/handlers/autocomplete.js#L36-L43
5) This is not needed `.slice(0, Math.min(AUTOCOMPLETE_NUM, tempArr.length))` you can just do `.slice(0, AUTOCOMPLETE_NUM)`

**Comment by Diabolicah** [comment]
Fixed in commit b19c3183fa5c72be81ef93f10d785a7fe60f2c28
